spring.application.name=atlas

aws.region=eu-north-1

atlas.max.agent.steps = 10
atlas.streaming.timeout = 2m

atlas.chunk.size = 400
atlas.chunk.overlap = 50

atlas.knowledge.location=classpath*:knowledge/*

spring.datasource.url=jdbc:postgresql://localhost:5432/atlas
spring.datasource.username=atlas
spring.datasource.password=atlas
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog-master.yaml


